use_frameworks!

platform :ios, '12.0'

target 'deeplinking_Example' do
  pod 'deeplinking', :path => '../'

  pod 'AppsOnAirIOSCore', :git => 'https://github.com/harshil-gandhi-us/AppsOnAirIOSCore', :branch=>'dev'

  target 'deeplinking_Tests' do
    inherit! :search_paths

    
  end
end
